### ISSUE TITLE
Template key is not reliable

### ISSUE THREAD

**Issue by ysegorov** [trueadm/t7#1]
Just a note on template key generation.

Considering this strange code

```javascript
var s = 1,
    a = t7`<ul>${s}</ul>`,
    b = t7`<ol>${s}</ol>;
console.log(a, b);
```
we will have the following in console
```javascript
Object { tag: "ul", attrs: Object, children: "1" } Object { tag: "ul", attrs: Object, children: "1" }
```
As for the library - excellent idea, Dominic! :)

**Comment by trueadm** [comment]
Thanks for trying t7 out and thank you for finding that bug. :)

**Comment by joelrich** [comment]
@trueadm Why don't you just use template.join() for the cache key?

**Comment by trueadm** [comment]
@joelrich  Large strings for cache key results in slower lookup times than hashed results.

**Comment by joelrich** [comment]
Have you verified that? I am asking because such property access of is very likely implemented as a hashtable (which does basically the same, just implemented in C).

**Comment by trueadm** [comment]
In C, you have a limit on hashtables in terms of the key. Same applies here, especially with very large strings.

**Comment by aMarCruz** [comment]
1k is ok? how about this:

```javascript
  key = +(new Date()) + template.join().substring(0,1024);
```
