### ISSUE TITLE
tests not working in windows environment

### ISSUE THREAD

**Issue by Kflash** [trueadm/t7#15]
Got a error message telling me that the babel-loader are not loaded, and can't resolve the module 'react'.
I do the same here as in Inferno, and in Inferno this works.

`
[84] ./~/babel-loader!./tests/tests.js 5.16 kB {0} [built] [1 error]
`

```
ERROR in ./~/babel-loader!./tests/tests.js
Module not found: Error: Cannot resolve module 'react' in C:\xxxt7\tests
 @ ./~/babel-loader!./tests/tests.js 29:13-29
```

**Comment by trueadm** [comment]
Fixed in latest push

**Comment by Kflash** [comment]
@trueadm Not fixed at all, got even worse !!

**Comment by trueadm** [comment]
Make sure you do npm install again.
