### ISSUE TITLE
React-native (android) does not appear to be supported

### ISSUE THREAD

**Issue by vladp** [trueadm/t7#19]
Running the example through, I am getting

> ReactNativeJS: Can't find variable: document
> node_modules/t7/t7.js:14

Is react-native intended to be supported, or this is out-of-scope for t7?

thank you

**Comment by trueadm** [comment]
Hi @vladp, React Native should be supported – the document variable should be checked via `typeof`. If you think you can fix this easily enough with a PR, I'd be happy to merge it. If not, it's something I can look into later in the week. Thanks!

**Comment by vladp** [comment]
Hi @trueadm I had attempted to  make minor update as you suggested,  in the pull request. But as you commented on there, in addition to my initial misunderstanding, there could be other actual  issues.  I have the environment setup to test, so happy to continue, if you have time to assist.

**Comment by trueadm** [comment]
This has been tested lately and works.
