### ISSUE TITLE
Any way to handle splats (spread operator)

### ISSUE THREAD

**Issue by a-s-o** [trueadm/t7#23]
Hi, thanks for you work on this library. I have just started using it and I like the way that components are handled.

I am wondering if there is any way to handle splats. They are useful in JSX for higher order components. For example doing the following in JSX:

```javascript
function Component (props) {
  return (
    <input class='Input'  onInput={this.onInput} {...props} />
  );
}
```

Effectively, we don't know or don't care about the income props (or whatever arbitrary object) and we want to simply relay it down to a tag. If not supported, would you consider adding this? I can attempt a pull request if you are interested.

I suppose we could check whether a preceding literal ends with `...` and then assign the immediately following substitution to the props. For example:

```javascript
<input class='Input' onInput=${this.onInput} ...${props} />
```

**Comment by trueadm** [comment]
I'd be happy to take a PR for this addition :)
