### ISSUE TITLE
Example from readme.md does not work

### ISSUE THREAD

**Issue by maximecaron** [trueadm/t7#3]
To render correctly in cito.js it should look like this:

{"tag":"div","attrs":{"class":"foo"},"children":[{"tag":"h1","attrs":{},"children":["Hello ","World"]},{"tag":"ul","attrs":{"id":"bar"},"children":[{"tag":"li","attrs":{"class":"item"},"children":[{"tag":"span","attrs":{},"children":["The item is: ","Ball"]}]},{"tag":"li","attrs":{"class":"item"},"children":[{"tag":"span","attrs":{},"children":["The item is: ","Boat"]}]}]}]}

but currently returning this instead:

{"tag":"div","attrs":{"class":"foo"},"children":[{"tag":"h1","attrs":{},"children":["Hello ","World"]},{"tag":"ul","attrs":{"id":"bar"},"children":[[{"tag":"li","attrs":{"class":"item"},"children":[{"tag":"span","attrs":{},"children":["The item is: ","Ball"]}]},{"tag":"li","attrs":{"class":"item"},"children":[{"tag":"span","attrs":{},"children":["The item is: ","Boat"]}]}]]}]}

**Comment by trueadm** [comment]
Hi maximecaron, this has now been fixed in the latest commit :) thank you for reporting it.

**Comment by maximecaron** [comment]
Hi Dominic,
 Thanks a lot for the quick fix.
 I was wondering if you could add instruction on how to run the precompiler.
 I wanted to try it but it was not clear to me how to use it.

Cheer!
Maxime Caron

**Comment by trueadm** [comment]
Ah, I wasn't meant to merge that version of the compiler as there was a big bug found in the precompiler that I need to fix before it's usable again (broke several refactors ago). I'm probably going to branch that precompiler off into a separate repo at some stage as I feel it's a beast in its own right. I'll be sure to let you know once it's available again to play with :)

**Comment by maximecaron** [comment]
Ok perfect,
Thanks.

On Fri, Jul 10, 2015 at 11:35 AM, Dominic Gannaway <notifications@github.com
