### ISSUE TITLE
fix builds and make t7 isomorphic

### ISSUE THREAD

**Issue by edge** [trueadm/t7#7]
We had a nice talk over in https://github.com/trueadm/inferno/issues/9.

I've attempted to switch to switch t7 over to the ES6 module system here: https://github.com/edge/t7.

I ran into several problems, which I think stem from the fact that t7 uses some weird optimization trick. In any case, imports don't work as expected.

Another issue is that t7 currently checks for browser instances of React/Mithril. Most people use a build system to bundle those nowadays, so it won't be very useful. I think you could also improve performance by taking out those checks, and instead separating them into libraries like `t7/react`, `t7/mithril`, `t7/inferno`, `t7/universal`, etc.

This would make people much more inclined to use t7.

**Comment by trueadm** [comment]
@edge awesome stuff. I did plan to take out the different support (with maybe the exception of Universal, as that should be the "default"). It would also tidy up the code quite a bit.

I was also looking into ways of constructing the compiled JavaScript without hacking around with arrays, but they do seem quite performant compared to some other methods that other authors have used to construct compiled templates. Would be great to also chat directly to you if possible, do you use Skype?

**Comment by edge** [comment]
I haven't used it in a while. Would Gmail work?

encryptedredux@gmail.com

**Comment by edge** [comment]
Added a build system to `next` branch. We'll continue in #11 focusing on isomorphic support.
